import { GameBoard } from './index.js'

const game = GameBoard(8)
game.possibleMoves()
console.log(game.printBoard())
console.log('-------------------------------------------')
game.knightMoves([3, 3], [0, 0])
// console.log(`True === ${game.validSource([0, 0])}`)
// console.log(`False === ${game.validSource([-1, 0])}`)
// console.log(`False === ${game.validSource([0, -3])}`)
// console.log(`False === ${game.validSource([8, 0])}`)
// console.log(`False === ${game.validSource([0, 8])}`)
// console.log(`False === ${game.validSource([-1, 9])}`)
// console.log(`False === ${game.validSource([8, -5])}`)
// console.log(`True === ${game.validSource([3, 7])}`)
// console.log(`True === ${game.validSource([1, 2])}`)
// console.log(`False === ${game.validSource([0])}`)
// console.log(`False === ${game.validSource([])}`)
// console.log(`False === ${game.validSource([{}, 2])}`)
